apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
      version: green
  template:
    metadata:
      labels:
        app: nodejs-app
        version: green
    spec:
      containers:
      - name: nodejs-app
        image: public.ecr.aws/docker/library/node:14
        command: ["sh", "-c"]
        args:
          - |
            echo 'const express = require("express");
            const app = express();
            app.get("/", (req, res) => {
              res.send("Hello World from GREEN version");
            });
            app.listen(3000, () => {
              console.log("App listening on port 3000");
            });' > app.js
            npm install express
            node app.js
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "green"