controller:
  JCasC:
    defaultConfig: true
  installPlugins:
    - kubernetes:1.31.3
    - workflow-aggregator:2.6
    - git:4.11.3
    - blueocean:1.25.3
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  javaOpts: "-Xmx1500m"
  servicePort: 80
  serviceType: LoadBalancer
agent:
  podTemplate:
    containers:
    - name: jnlp
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
persistence:
  enabled: true
  size: 10Gi